name: Open Journal Retraction Notice
description: Retract a paper publishing a retraction notice
inputs:
  issue_id:
    description: The review issue id for the paper to be retracted
    required: true
  retraction_notice_url:
    description: URL for the markdown file of the retraction notice
    required: true
  journal:
    description: The journal to use for the preprint. Default is 'joss'.
    required: false
    default: joss
  mode:
    description: Set the compiled retraction notice as a draft or as a final published paper. Posible values are 'draft' or 'final'.
    required: false
    default: draft
runs:
  using: "composite"
  env:
    ISSUE_ID: ${{ inputs.issue_id }}
    JOURNAL_ALIAS: ${{ inputs.journal }}
    RETRACTION_NOTICE_URL: ${{ inputs.retraction_notice_url }}
    BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
        cache-version: retraction
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Prepare retraction metadata
      id: retraction-metadata
      shell: bash
      run: |
        bundle exec ruby ${{ github.action_path }}/prepare_retraction_metadata.rb
    - name: Build retraction notice
      id: build-retraction
      uses: xuanxu/publishing-artifacts-action@main
      with:
        paper-path: ${{ steps.retraction-metadata.outputs.retraction_notice_path }}
        args: ${{steps.retraction-metadata.outputs.inara_args}}
    - name: Process retraction notice
      id: process-retraction
      shell: bash
      run: |
        bundle exec ruby ${{ github.action_path }}/process_retraction_notice.rb
    - uses: actions/upload-artifact@v3
      if: ${{ success() && inputs.mode != 'final' }}
      with:
        name: retraction-test-${{ inputs.journal }}-${{ inputs.issue_id }}
        path: ${{ steps.build-retraction.outputs.paper_file_path }}
        retention-days: 1
branding:
  icon: file-minus
  color: red
