name: Open Journal Retraction Notice
description: Retract a paper publishing a retraction notice
inputs:
  issue_id:
    description: The review issue id for the paper to be retracted
    required: true
  retraction_notice_url:
    description: URL for the markdown file of the retraction notice
    required: true
  journal:
    description: The journal where the retracted paper is published. Default is 'joss'.
    required: false
    default: joss
  papers_repo:
    description: The repository for the published papers. Default is 'openjournals/joss-papers'
    required: false
    default: openjournals/joss-papers
  papers_repo_main_branch:
    description: The name of the repo's main branch to issue the pull request against
    required: false
    default: "main"
  branch_prefix:
    description: The prefix to add to the name of all branches
    required: false
    default: ""
  github_bot_token:
    description: The GitHub access token to be used to upload files
    required: false
  journal_secret:
    description: The access token to be used to deposit the paper
    required: true
  crossref_username:
    description: Crossref username doing the deposit
    required: true
  crossref_password:
    description: Crossref password
    required: true
  crossref_mode:
    description: Use test or production crossref calls
    required: false
    default: ""
  mode:
    description: Set the compiled retraction notice as a draft or as a final published paper. Posible values are 'draft' or 'final'.
    required: false
    default: draft
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
        cache-version: retraction
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Prepare retraction metadata
      id: retraction-metadata
      shell: bash
      env:
        ISSUE_ID: ${{ inputs.issue_id }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        RETRACTION_NOTICE_URL: ${{ inputs.retraction_notice_url }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/prepare_retraction_metadata.rb
    - name: Build retraction notice
      uses: xuanxu/publishing-artifacts-action@main
      with:
        paper-path: ${{ steps.retraction-metadata.outputs.retraction_notice_path }}
        args: ${{steps.retraction-metadata.outputs.inara_args}}
    - name: Create artifact with generated files
      uses: actions/upload-artifact@v3
      if: ${{ success() && inputs.mode != 'final' }}
      with:
        name: retraction-test-${{ inputs.journal }}-${{ inputs.issue_id }}
        path: |
          paper.pdf
          paper.crossref
          paper.jats
        retention-days: 1
    - name: Validate retraction metadata
      shell: bash
      env:
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/validate_retraction_metadata.rb
    - name: Deposit retraction notice with Open Journals
      if: ${{ success() && inputs.mode == 'final' }}
      shell: bash
      env:
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
        BOT_TOKEN: ${{ inputs.github_bot_token }}
        ISSUE_ID: ${{ inputs.issue_id }}
        JOURNAL_ALIAS: ${{ inputs.journal }}
        JOURNAL_SECRET: ${{ inputs.journal_secret }}
        PAPERS_REPO: ${{ inputs.papers_repo }}
        PAPERS_REPO_MAIN_BRANCH: ${{ inputs.papers_repo_main_branch }}
        BRANCH_PREFIX: ${{ inputs.branch_prefix }}
      run: |
        bundle exec ruby ${{ github.action_path }}/deposit_retraction_notice.rb
    - name: Deposit retraction notice with Crossref
      uses: xuanxu/deposit-with-crossref-action@main
      if: ${{ success() && inputs.mode == 'final' }}
      with:
        crossref_filepath: paper.crossref
        crossref_username: ${{ inputs.crossref_username }}
        crossref_password: ${{ inputs.crossref_password }}
        crossref_mode: ${{ inputs.crossref_mode }}
branding:
  icon: file-minus
  color: red
